app: app_89L1xne6sL5
signing-key: ~/equinox.key
token: 4kj5ypgZYWUF7UR7sUWA4qGdHA8qu1fWqAkr17ounAdfi5nfz3x
platforms: [
	linux_amd64, linux_386,
	windows_amd64, windows_386,
	darwin_amd64, darwin_386,
	netbsd_amd64, netbsd_386,
	freebsd_amd64, freebsd_386,
	solaris_amd64
]
